#!/bin/sh

echo "Executing /etc/qemu-ifup"
echo "Bringing up $1 for bridged mode..."
sudo /usr/bin/ip link set $1 up promisc on
echo "Adding $1 to wrtbridge1..."
sudo /usr/bin/brctl addif wrtbridge1 $1
sleep 2
